[env]
release = "dev"

[opcua]
endpoint = "opc.tcp://opcserver:4840"
interval = 500      # 读取间隔，单位 milliseconds

[openapi]
deploy_host = "localhost:8080"       # 部署到目标位置   http://localhost:8080/docs/index.html#/ 访问 API 文档
port = 8080      

[db]
type = "sqlite"           # "postgres"
POSTGRES_HOST = "db"
POSTGRES_USER = "postgres"
POSTGRES_DB = "postgres"
POSTGRES_PASSWORD = "postgres"
