[opcua]
endpoint = "opc.tcp://opcserver:4840"
interval = 500      # 读取间隔，单位 milliseconds

[openapi]
deploy_host = "localhost:8080"       # 部署到目标位置
port = 8080       # 打开  http://localhost:8080/docs/index.html#/ 访问 API 文档