version: '3.8'


services:
  opc-plugin-server:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - git_test=1
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD","/healthcheck" ]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 8s