basePath: /
definitions:
  alicerouters.ApiResponse:
    properties:
      message:
        example: pong
        type: string
    type: object
  routers.AddNodeToReadRequest:
    properties:
      data-type:
        example: Int32
        type: string
      name:
        example: MyVariable
        type: string
      node-id:
        example: ns=2;s=MyVariable
        type: string
    required:
    - name
    - node-id
    type: object
  routers.AddNodeToReadResponse:
    properties:
      code:
        example: 200
        type: integer
      data:
        example: ""
        type: string
      message:
        example: 节点添加成功
        type: string
    type: object
  routers.ApiResponse:
    properties:
      message:
        example: 欢迎使用OPC-UA OpenAPI
        type: string
    type: object
  smithrouters.ApiResponse:
    properties:
      message:
        example: pong
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: advanced_to@163.com
  description: OPC-UA转http协议
  title: OPC-UA Open API
  version: "1.0"
paths:
  /api/v1/:
    get:
      consumes:
      - application/json
      description: 根路由
      produces:
      - application/json
      responses:
        "200":
          description: 欢迎使用OPC-UA OpenAPI
          schema:
            $ref: '#/definitions/routers.ApiResponse'
      summary: 根路由
      tags:
      - default
  /api/v1/add-node-to-read:
    post:
      consumes:
      - application/json
      description: AddNodeToRead 路由
      parameters:
      - description: 见下方JSON
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/routers.AddNodeToReadRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 节点添加成功
          schema:
            $ref: '#/definitions/routers.AddNodeToReadResponse'
      security:
      - BearerAuth: []
      summary: AddNodeToRead 路由
      tags:
      - default
  /api/v1/alice/ping:
    get:
      consumes:
      - application/json
      description: Ping 路由
      produces:
      - application/json
      responses:
        "200":
          description: pong
          schema:
            $ref: '#/definitions/alicerouters.ApiResponse'
      summary: Ping 路由
      tags:
      - alice的接口
  /api/v1/ping:
    get:
      consumes:
      - application/json
      description: Ping 路由
      produces:
      - application/json
      responses:
        "200":
          description: pong
          schema:
            $ref: '#/definitions/routers.ApiResponse'
      security:
      - BearerAuth: []
      summary: Ping 路由
      tags:
      - default
  /api/v1/smith/ping:
    get:
      consumes:
      - application/json
      description: Ping 路由
      produces:
      - application/json
      responses:
        "200":
          description: pong
          schema:
            $ref: '#/definitions/smithrouters.ApiResponse'
      summary: Ping 路由
      tags:
      - smith的接口
schemes:
- http
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
